### ISSUE TITLE
Copy Sequence, Multiple Alignment, and Tree format files to GitHub site

### ISSUE THREAD

**Issue by bosborne** [bioperl/bioperl.github.io#15]
Have started this ....

**Comment by cjfields** [comment]
Just a note (and not to dissuade this) but we had at one point discussed moving these to Wikipedia since they aren't BioPerl-specific.  This is in a manner similar to the Wikipedia FASTQ article.  It's a good idea to get them off the wiki regardless which direction we take, though, can always decide what to do after.

**Comment by bosborne** [comment]
Good idea. Some work has been done in this regard, but most are missing:

https://en.wikipedia.org/wiki/Category:Biological_sequence_format

**Comment by bosborne** [comment]
Pages are copied from the Wiki now and correct, whether they move to Wikipedia is a separate issue.
