### ISSUE TITLE
Correct and update INSTALL.WIN

### ISSUE THREAD

**Issue by bosborne** [bioperl/bioperl.github.io#20]

**Comment by pcantalupo** [comment]
i'm starting this

**Comment by bosborne** [comment]
Cool. You probably noticed that I tried to make INSTALL in bioperl-live identical to INSTALL.md in bioperl.github.io, except for some Markdown formatting. The same should be true of INSTALL.WIN, we should be able to take it, add some formatting, and that becomes INSTALL.WIN.md in the Web site.

**Comment by pcantalupo** [comment]
I created a pull request https://github.com/bioperl/bioperl.github.io/pull/26 for my changes. Can you have a look? There seem to be some outdated links such as http://rage.against.org/installingdbdmysqlInCygwin. Also, there are many links back to bioperl.org/wiki; will these be preserved? If the formatting seems OK to you please merge.

**Comment by bosborne** [comment]
Did the merge. Also removed lots of old material, or extraneous material. Are you a Windows user? Do you know if the Strawberry Perl or Activestate instructions are correct? They are very old.

**Comment by bosborne** [comment]
You asked about links back to the Wiki. I don't think it would be wise to try to maintain the Wiki in any way. We don't have enough resources to keep the Wiki and this new site in sync, and the Wiki is a security liability. My personal view is that this new site should be very simple and easy to maintain, so we copy over only the important content from the Wiki, then close the Wiki.

**Comment by pcantalupo** [comment]
https://github.com/bioperl/bioperl.github.io/issues/20#issuecomment-163950962
I use bioperl in cygwin but I must confess that I don't formally install bioperl. I git clone bioperl-live and leave it be. Never used Strawberry nor Activestate.

**Comment by fjossandon** [comment]
Hello,

I’m a Windows user and I have used both Strawberry and ActiveState (I started with ActiveState and then dropped it in favor of Strawberry). In fact I updated the installation instructions for Windows in the past, although I presently use PERL5LIB to use the folder with the cloned repo instead of installing.

I’ll try to get some time to test if the Windows installation instructions still works and tell you if I found any problem.

Cheers,

Francisco J. Ossandón

De: Paul Cantalupo [mailto:notifications@github.com] 
Enviado el: viernes, 11 de diciembre de 2015 12:48
Para: bioperl/bioperl.github.io bioperl.github.io@noreply.github.com
Asunto: Re: [bioperl.github.io] Correct and update INSTALL.WIN (#20)

#20 (comment) https://github.com/bioperl/bioperl.github.io/issues/20#issuecomment-163950962 
I use bioperl in cygwin but I must confess that I don't formally install bioperl. I git clone bioperl-live and leave it be. Never used Strawberry nor Activestate. 

—
Reply to this email directly or view it on GitHub https://github.com/bioperl/bioperl.github.io/issues/20#issuecomment-163969757 .

---

El software de antivirus Avast ha analizado este correo electrónico en busca de virus.
https://www.avast.com/antivirus

**Comment by majensen** [comment]
Awesome!

On Fri, Dec 11, 2015 at 10:55 AM, Francisco J. Ossandon < notifications@github.com [notifications@github.com] > wrote:
Hello,

I’m a Windows user and I have used both Strawberry and ActiveState (I started
with ActiveState and then dropped it in favor of Strawberry). In fact I updated
the installation instructions for Windows in the past, although I presently use
PERL5LIB to use the folder with the cloned repo instead of installing.

I’ll try to get some time to test if the Windows installation instructions still
works and tell you if I found any problem.

Cheers,

Francisco J. Ossandón

De: Paul Cantalupo [mailto:notifications@github.com]
Enviado el: viernes, 11 de diciembre de 2015 12:48
Para: bioperl/bioperl.github.io bioperl.github.io@noreply.github.com
Asunto: Re: [bioperl.github.io] Correct and update INSTALL.WIN (#20)

#20 (comment)
https://github.com/bioperl/bioperl.github.io/issues/20#issuecomment-163950962
I use bioperl in cygwin but I must confess that I don't formally install
bioperl. I git clone bioperl-live and leave it be. Never used Strawberry nor
Activestate.

—
Reply to this email directly or view it on GitHub
https://github.com/bioperl/bioperl.github.io/issues/20#issuecomment-163969757
.

---

El software de antivirus Avast ha analizado este correo electrónico en busca de
virus.
https://www.avast.com/antivirus
—
Reply to this email directly or view it on GitHub
[https://github.com/bioperl/bioperl.github.io/issues/20#issuecomment-163973684] .[https://github.com/notifications/beacon/AAFAmR5QQamnGfKaNR_nsxZxHu8C6OtHks5pOuoHgaJpZM4GyzEE.gif]

**Comment by bosborne** [comment]
Thank you Francisco. We're trying to create documentation now that is simple - but correct - and easy to maintain. I'm remembering that at one point we thought we'd just go with Strawberry Perl and not discuss ActiveState. I suggest that if you don't know if the ActiveState sections are correct or not that you just remove them.

**Comment by fjossandon** [comment]
Hello Brian,

I finished checking the installing steps for both ActivePerl and Strawberry and updated the INSTALL.WIN.md file in the “instwin” branch to complement Paul edits, so they are incorporated when the branch is merged.

I dropped all ActiveState PPM installation support in favor of CPAN. Actually, ActivePerl is very troublesome, not only because the last 5.22 version was released 5 months ago and the PPM4 packages for that version are still not released (so had to downgrade to 5.20 to install MinGW), but after I uninstalled it and completely removed its folder, I installed Strawberry Perl and used CPAN, and then I realized that now the cpan> is checking ActiveState mirror and downloading modules from there instead from CPAN, so it probably made some registry editing that was not removed on uninstall.

I only edited sections 1 to 4, but I think that many of the other sections needs to also be updated (remove all places mentioning ActiveState PPM for example, change nmake for dmake) or moved to a better place (the 5 Bioperl section shouldn’t go in another file, maybe in the main INSTALL??) or maybe removed. For example, Cygwin is not as mandatory as before since Strawberry provides the functionality. Unfortunately, now I don’t have enough time to go through the other sections properly, so it would be great if somebody else could check those. :(

Cheers,

Francisco J. Ossandon

De: Brian Osborne [mailto:notifications@github.com] 
Enviado el: sábado, 12 de diciembre de 2015 11:32
Para: bioperl/bioperl.github.io bioperl.github.io@noreply.github.com
CC: Francisco J. Ossandon fco.j.ossandon@gmail.com
Asunto: Re: [bioperl.github.io] Correct and update INSTALL.WIN (#20)

Thank you Francisco. We're trying to create documentation now that is simple - but correct - and easy to maintain. I'm remembering that at one point we thought we'd just go with Strawberry Perl and not discuss ActiveState. I suggest that if you don't know if the ActiveState sections are correct or not that you just remove them.

—
Reply to this email directly or  https://github.com/bioperl/bioperl.github.io/issues/20#issuecomment-164158523 view it on GitHub.

---

El software de antivirus Avast ha analizado este correo electrónico en busca de virus.
https://www.avast.com/antivirus

**Comment by bosborne** [comment]
Francisco,

Thank you for updating this, now we can be more confident about the content. What I’ll do is take your sections 1 to 4, and make them sections 1 to 4 in the master branch. You’re absolutely right about sections 5 and greater, they have been heavily edited or entirely removed in the master branch.

Thanks again,

Brian O.

**Comment by bosborne** [comment]
Incorporated Francisco's changes.
